name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
    - run: curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 && sudo mv tailwindcss-linux-x64 /usr/bin/tailwindcss && sudo chmod +x /usr/bin/tailwindcss
    - run: cd frontend && npm install && cd ..
    - run: cargo build --verbose
    
